version: '3'
services:
    myapp:
        image: test-app:latest
        networks:
            - test
        ports:
            - 8080:8080
        depends_on:
            - mysql
        environment:
            DB_HOST: mysql
            DB_PORT: 3306
            DB_USER: user
            DB_PASSWORD: password
            DB_DATABASE: test
            API_PORT: 8080
        command: ['yarn', 'start:local']

    mysql:
        image: mysql:8.2.0
        networks:
            - test
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: test
        volumes:
            - ./mysql/init:/docker-entrypoint-initdb.d

networks:
    test:
        driver: bridge
